### ISSUE TITLE
[QUESTION] CRD compatibility

### ISSUE THREAD

**Issue by git-hyagi** [git-hyagi/pulp-operator-go#22]
Not every field from `pulp-operator-go` has the same name/structure than `pulp-operator`.
For example, `pulp-operator` has no `database` struct, but we are "_better organizing_" the database related configurations in a `database` field in this project.

Should we keep the exact same format from `pulp-operator` CRD to ease a possible migration or should we consider them incompatible (like upgrading an api from v1 to v2)?

**Comment by fao89** [comment]
Good queston!
I think it would be ok to be a breaking change and use this ansible->go to improve things,
we just need to communicate well, it will be a breaking change
